male_suffixes:
  - "ов"
  - "ев"
  - "ин"
  - "ский"
  - "цкий"
  - "ич"
female_suffixes:
  - "ова"
  - "ева"
  - "ина"
  - "ская"
  - "цкая"
common_male_names:
  - "вася"
  - "петя"
  - "дима"
  - "макс"
  - "иван"
  - "коля"
  - "саша"
  - "антон"
  - "сергей"
  - "андрей"
common_female_names:
  - "маша"
  - "аня"
  - "катя"
  - "оля"
  - "настя"
  - "даша"
  - "лена"
  - "юля"
  - "тан"
  - "ксюша"
